spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/takemehome
    username: take
    password: take

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
